"""Monitor and live-query the public Hugging Face deployment."""

from __future__ import annotations

import json
import re
from pathlib import Path

from gradio_client import Client
from huggingface_hub import HfApi, hf_hub_download

MODEL_ID = "marcoharuni95/jax-addition-transformer-10m"
SPACE_ID = "marcoharuni95/jax-addition-transformer"
SPACE_URL = "https://marcoharuni95-jax-addition-transformer.hf.space"
MODEL_CARD_URL = f"https://huggingface.co/{MODEL_ID}"
SPACE_CARD_URL = f"https://huggingface.co/spaces/{SPACE_ID}"
ROOT = Path(__file__).resolve().parents[3]


def text_content(value) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        if "text" in value and isinstance(value["text"], str):
            return value["text"]
        return "\n".join(text_content(item) for item in value.values())
    if isinstance(value, (list, tuple)):
        return "\n".join(text_content(item) for item in value)
    return ""


def fetch_text_files(api: HfApi, repo_id: str, repo_type: str) -> dict[str, str]:
    allowed = {".py", ".md", ".txt", ".json", ".csv"}
    result = {}
    for name in api.list_repo_files(repo_id, repo_type=repo_type):
        if Path(name).suffix.lower() not in allowed:
            continue
        path = hf_hub_download(repo_id, name, repo_type=repo_type)
        result[name] = Path(path).read_text(errors="replace")
    return result


def assert_safe_text(files: dict[str, str]) -> None:
    joined = "\n".join(files.values())
    if re.search(r"/(?:home|Users)/[^/\s]+", joined):
        raise AssertionError("uploaded text contains a local absolute path")
    if re.search(r"\bhf_[A-Za-z0-9]{20,}\b", joined):
        raise AssertionError("uploaded text appears to contain a Hugging Face token")


def main() -> None:
    api = HfApi()
    runtime = api.wait_for_space(SPACE_ID, timeout=1200, poll_interval=10)
    stage = str(runtime.stage)
    print(f"Space stage: {stage}")
    if stage != "RUNNING":
        print("--- build logs ---")
        print("\n".join(api.fetch_space_logs(SPACE_ID, build=True)))
        print("--- runtime logs ---")
        print("\n".join(api.fetch_space_logs(SPACE_ID)))
        raise RuntimeError(f"Space did not reach RUNNING: {stage}")

    client = Client(SPACE_URL)
    cases = {
        "347 + 928": "1275",
        "What is 499 plus 501?": "1000",
        "Please add 91 and 909": "1000",
        "999 + 999": "1998",
    }
    live_results = {}
    for prompt, expected in cases.items():
        response = client.predict(prompt, [], api_name="/submit")
        content = text_content(response)
        if f"<strong>{expected}</strong>" not in content:
            raise AssertionError(f"live response for {prompt!r} did not contain {expected}: {content}")
        if "Generated by the 10M-parameter transformer" not in content:
            raise AssertionError("live response did not identify transformer generation")
        live_results[prompt] = expected

    unsupported = client.predict("12 * 3", [], api_name="/submit")
    unsupported_text = text_content(unsupported)
    if "Unsupported request" not in unsupported_text or "addition only" not in unsupported_text:
        raise AssertionError(f"unsupported request was not rejected clearly: {unsupported_text}")

    model_info = api.repo_info(MODEL_ID, repo_type="model")
    space_info = api.repo_info(SPACE_ID, repo_type="space")
    if model_info.private or space_info.private:
        raise AssertionError("both Hugging Face repositories must be public")

    model_files = fetch_text_files(api, MODEL_ID, "model")
    space_files = fetch_text_files(api, SPACE_ID, "space")
    assert_safe_text(model_files)
    assert_safe_text(space_files)
    if SPACE_CARD_URL not in model_files["README.md"]:
        raise AssertionError("model card does not link to the Space")
    if MODEL_CARD_URL not in space_files["README.md"]:
        raise AssertionError("Space card does not link to the model")
    if MODEL_ID not in space_files["model_runtime.py"]:
        raise AssertionError("Space runtime is not bound to the published model repository")
    if "hf_hub_download" not in space_files["inference.py"]:
        raise AssertionError("Space does not download the model artifact through huggingface_hub")

    result = {
        "runtime_stage": stage,
        "model_sha": model_info.sha,
        "space_sha": space_info.sha,
        "live_results": live_results,
        "unsupported_request": "gracefully rejected",
        "model_public": not model_info.private,
        "space_public": not space_info.private,
        "space_url": SPACE_URL,
    }
    output = ROOT / ".local" / "hf-deployment" / "public-verification.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
