"""Public Gradio interface for the released JAX addition transformer."""

from __future__ import annotations

import html

import gradio as gr

from input_parser import InputError, parse_addition
from model_runtime import get_model

MODEL_URL = "https://huggingface.co/marcoharuni95/jax-addition-transformer-10m"
SOURCE_URL = "https://github.com/marcoharuni/jax-addition-transformer"

MODEL = get_model()


def respond(message: str, history: list[dict[str, str]] | None):
    conversation = list(history or [])
    visitor_message = message.strip() if isinstance(message, str) else ""
    conversation.append({"role": "user", "content": visitor_message})
    try:
        a, b = parse_addition(visitor_message)
        details = MODEL.add_with_details(a, b)
        answer = html.escape(str(details["answer"]))
        prompt = html.escape(str(details["prompt"]))
        internal = html.escape(str(details["internal_digits"]))
        latency_ms = float(details["latency_seconds"]) * 1000
        content = (
            f"<div class='model-answer'><strong>{answer}</strong></div>\n\n"
            f"Generated by the 10M-parameter transformer in {latency_ms:.1f} ms.\n\n"
            "<details><summary>Technical details</summary>\n\n"
            f"- Normalized prompt: `{prompt}`\n"
            f"- Generated internal digits: `{internal}` (units first)\n"
            "</details>"
        )
    except InputError as exc:
        content = f"**Unsupported request.** {html.escape(str(exc))}"
    except Exception:
        content = (
            "**The model could not complete this request.** "
            "Please try again with two integers from 0 to 999."
        )
    conversation.append({"role": "assistant", "content": content})
    return "", conversation


with gr.Blocks(title="JAX Addition Transformer") as demo:
    gr.HTML(
        """
        <header id="masthead">
          <p class="eyebrow">A complete-domain arithmetic experiment</p>
          <h1>JAX Addition Transformer</h1>
          <p class="deck">
            A 10,000,000-parameter decoder-only transformer trained for fixed
            three-digit addition. Every answer shown here is generated
            autoregressively by the released JAX checkpoint.
          </p>
        </header>
        """
    )
    gr.HTML(
        """
        <div id="domain-notice">
          <strong>Domain:</strong> addition only; each operand must be a whole
          number from 0 through 999.
        </div>
        """
    )
    chatbot = gr.Chatbot(
        value=[
            {
                "role": "assistant",
                "content": (
                    "Ask me to add two integers—for example, **347 + 928**. "
                    "I normalize a few clear phrasings into the model’s fixed-width prompt."
                ),
            }
        ],
        elem_id="conversation",
        height=410,
        layout="bubble",
        placeholder="The transformer is ready.",
        show_label=False,
    )
    with gr.Row():
        message = gr.Textbox(
            placeholder="Try: What is 499 plus 501?",
            show_label=False,
            elem_id="composer",
            scale=8,
            autofocus=True,
        )
        send = gr.Button("Send", variant="primary", elem_id="send-button", scale=1)
    gr.Examples(
        examples=[
            "347 + 928",
            "What is 499 plus 501?",
            "Please add 91 and 909",
            "999 + 999",
        ],
        inputs=message,
        label="Example prompts",
    )
    gr.HTML(
        f"""
        <section id="technical-panel">
          <strong>Technical note.</strong> Five decoder blocks · width 320 ·
          five attention heads · learned positions · tied token head · greedy
          four-token generation. Initial CPU compilation took
          {MODEL.compilation_seconds:.2f} s; subsequent request latency is shown
          with each answer.
          <br><br>
          <a href="{MODEL_URL}" target="_blank">Model card and weights</a>
          &nbsp;·&nbsp;
          <a href="{SOURCE_URL}" target="_blank">Source repository</a>
        </section>
        """
    )

    send.click(
        respond,
        inputs=[message, chatbot],
        outputs=[message, chatbot],
        api_name="submit",
        concurrency_limit=1,
        show_progress="minimal",
    )
    message.submit(
        respond,
        inputs=[message, chatbot],
        outputs=[message, chatbot],
        api_name=False,
        concurrency_limit=1,
        show_progress="minimal",
    )

demo.queue(default_concurrency_limit=1, max_size=16)

if __name__ == "__main__":
    demo.launch(css_paths="assets/style.css", theme=gr.themes.Base())
