from pathlib import Path

from streamlit.testing.v1 import AppTest

APP = Path(__file__).resolve().parents[1] / "app.py"


def run_prompt(prompt: str) -> AppTest:
    app = AppTest.from_file(APP, default_timeout=30).run()
    app.chat_input[0].set_value(prompt).run()
    return app


def rendered_text(app: AppTest) -> str:
    return "\n".join(element.value for element in app.markdown) + "\n" + "\n".join(
        element.value for element in app.warning
    )


def test_page_structure_and_links():
    app = AppTest.from_file(APP, default_timeout=30).run()
    assert not app.exception
    assert len(app.chat_input) == 1
    assert len(app.button) == 4
    text = rendered_text(app)
    assert "JAX Addition Transformer" in text
    assert "10,000,000-parameter" in text
    assert "huggingface.co/marcoharuni95/jax-addition-transformer-10m" in text


def test_valid_chat_request_uses_generated_answer():
    app = run_prompt("347 + 928")
    assert not app.exception
    text = rendered_text(app)
    assert "1275" in text
    assert "5721" in text
    assert "Generated by the transformer" in text


def test_unsupported_operator_and_range_are_clear():
    multiplication = run_prompt("12 * 3")
    assert "addition only" in rendered_text(multiplication)
    out_of_range = run_prompt("1000 + 1")
    assert "between 0 and 999" in rendered_text(out_of_range)
