#!/usr/bin/env python3
"""Synchronize the pinned Colab setup cells from configs/colab-runtime.json."""

from __future__ import annotations

import json
from pathlib import Path

import nbformat


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "configs" / "colab-runtime.json"
NOTEBOOK_DIR = ROOT / "notebooks"
INSTALL_TAG = "colab-runtime-install"
VALIDATE_TAG = "colab-runtime-validate"
SMOKE_TAG = "colab-one-step-smoke"


SETUP_MARKDOWN = """## Setup — pinned Colab T4 runtime

1. Select **Runtime → Change runtime type → T4 GPU**.
2. Run the environment installation cell below. It uses `uv` to create one
   isolated, pinned CUDA 12 environment ahead of Colab's preinstalled packages.
3. Colab restarts the Python process exactly once. After it reconnects, choose
   **Runtime → Run all** (or rerun from this setup cell).
4. Continue only when the validation cell prints `Backend: gpu`.

JAX, JAXlib, the CUDA plugin, and Flax are pinned together. An unbounded
`jax[cuda12]` install can combine JAX 0.11.0 with Flax 0.12.2 and fail at
`from flax import nnx` because JAX 0.11.0 removed `jax.core.Effect`.
"""

SMOKE_MARKDOWN = """## One-step compatibility smoke test

This uses the real dataset, exact 10,000,000-parameter model, optimizer, loss,
checkpoint format, and greedy generation path. It updates a temporary parameter
tree exactly once, then discards it; the complete training state below remains
unchanged.
"""

SMOKE_SOURCE = """SMOKE_BATCH_SIZE = 8
_smoke_inputs, _smoke_targets = batcher.sample()
_smoke_inputs = jnp.asarray(_smoke_inputs[:SMOKE_BATCH_SIZE])
_smoke_targets = jnp.asarray(_smoke_targets[:SMOKE_BATCH_SIZE])

assert _smoke_inputs.shape == (SMOKE_BATCH_SIZE, MODEL_INPUT_LENGTH)
assert _smoke_targets.shape == (SMOKE_BATCH_SIZE, MODEL_INPUT_LENGTH)
assert parameter_count == 10_000_000

# Exactly one optimizer update on a temporary tree.
_smoke_params, _smoke_optimizer_state, _smoke_metrics = train_step(
    params,
    optimizer_state,
    _smoke_inputs,
    _smoke_targets,
)
jax.block_until_ready(_smoke_metrics["loss"])
assert bool(jax.device_get(_smoke_metrics["finite"]))

_smoke_eval_loss, _smoke_eval_accuracy = evaluate_teacher_forced(
    _smoke_params,
    _smoke_inputs,
    _smoke_targets,
)
_smoke_checkpoint_bytes = pickle.dumps(
    {
        "params": jax.device_get(_smoke_params),
        "step": 1,
        "validation": {
            "loss": float(_smoke_eval_loss),
            "token_accuracy": float(_smoke_eval_accuracy),
        },
        "parameter_count": parameter_count,
    }
)
_smoke_checkpoint = pickle.loads(_smoke_checkpoint_bytes)
assert set(_smoke_checkpoint) == {
    "params",
    "step",
    "validation",
    "parameter_count",
}
assert _smoke_checkpoint["parameter_count"] == 10_000_000

_smoke_restored_params = jax.tree.map(jnp.asarray, _smoke_checkpoint["params"])
_smoke_restored_model = nnx.merge(graphdef, _smoke_restored_params)
_smoke_logits = _smoke_restored_model(_smoke_inputs)
assert _smoke_logits.shape == (
    SMOKE_BATCH_SIZE,
    MODEL_INPUT_LENGTH,
    VOCAB_SIZE,
)
_smoke_generated, _smoke_valid = generate_from_params(
    _smoke_restored_params,
    _smoke_inputs[:, :PROMPT_LENGTH],
)
assert _smoke_generated.shape == (SMOKE_BATCH_SIZE, ANSWER_DIGITS)
assert _smoke_valid.shape == (SMOKE_BATCH_SIZE,)

print(
    "One-step smoke test passed | "
    f"loss {float(_smoke_metrics['loss']):.4f} | "
    f"evaluation loss {float(_smoke_eval_loss):.4f} | "
    f"generated shape {tuple(_smoke_generated.shape)}"
)

del (
    _smoke_params,
    _smoke_optimizer_state,
    _smoke_checkpoint_bytes,
    _smoke_checkpoint,
    _smoke_restored_params,
    _smoke_restored_model,
    _smoke_logits,
    _smoke_generated,
    _smoke_valid,
)
"""


def source_lines(source: str) -> list[str]:
    return source.splitlines(keepends=True)


def install_source(config: dict[str, object], requirements: list[str]) -> str:
    versions = config["versions"]
    assert isinstance(versions, dict)
    direct_names = {
        requirement.split("==", maxsplit=1)[0].split("[", maxsplit=1)[0]
        for requirement in requirements
    }
    expected = {
        name: versions[name]
        for name in sorted(
            direct_names
            | {
            "jax",
            "jaxlib",
            "jax-cuda12-plugin",
            "jax-cuda12-pjrt",
            }
        )
    }
    return f"""# Generated by scripts/sync_colab_runtime.py; do not hand-edit.
import importlib.metadata as _metadata
import importlib.util as _importlib_util
import json as _json
import os as _os
import platform as _platform
import shutil as _shutil
import signal as _signal
import site as _site
import subprocess as _subprocess
import sys as _sys
from pathlib import Path as _Path

_COLAB_FINGERPRINT = {config["fingerprint"]!r}
_EXPECTED_PYTHON = {config["python"]!r}
_UV_BOOTSTRAP_VERSION = {config["uv_bootstrap_version"]!r}
_REQUIREMENTS = {_json_literal(requirements)}
_EXPECTED_VERSIONS = {_json_literal(expected)}
_IN_COLAB = _importlib_util.find_spec("google.colab") is not None
_ENV_ROOT = _Path("/content/.jax-addition-transformer-colab")
_ENV_PYTHON = _ENV_ROOT / "bin" / "python"
_ENV_SITE_PACKAGES = (
    _ENV_ROOT
    / "lib"
    / f"python{{_sys.version_info.major}}.{{_sys.version_info.minor}}"
    / "site-packages"
)
_RESTART_MARKER = _ENV_ROOT / f".{{_COLAB_FINGERPRINT}}.json"
_PTH_PATH = _Path(_site.getsitepackages()[0]) / "00-jax-addition-colab.pth"
_PTH_CONTENT = (
    "import sys; "
    f"sys.path.insert(0, {{str(_ENV_SITE_PACKAGES)!r}})\\n"
)

if _ENV_SITE_PACKAGES.is_dir():
    _site.addsitedir(str(_ENV_SITE_PACKAGES))
    if str(_ENV_SITE_PACKAGES) in _sys.path:
        _sys.path.remove(str(_ENV_SITE_PACKAGES))
    _sys.path.insert(0, str(_ENV_SITE_PACKAGES))

print("Python:", _platform.python_version())
print("Operating system:", _platform.platform())
print("Google Colab:", _IN_COLAB)
_smi = _subprocess.run(
    ["nvidia-smi", "--query-gpu=name,driver_version", "--format=csv,noheader"],
    check=False,
    capture_output=True,
    text=True,
)
print("Accelerator:", _smi.stdout.strip() or "not detected")

if ".".join(map(str, _sys.version_info[:2])) != _EXPECTED_PYTHON:
    raise RuntimeError(
        f"This notebook requires Python {{_EXPECTED_PYTHON}}; "
        f"the active runtime is {{_platform.python_version()}}. "
        "Select Colab's latest runtime and reconnect."
    )
if _IN_COLAB and _smi.returncode != 0:
    raise RuntimeError(
        "No NVIDIA GPU is attached. Select Runtime → Change runtime type → T4 GPU."
    )

def _installed_version(distribution):
    try:
        return _metadata.version(distribution)
    except _metadata.PackageNotFoundError:
        return None

_mismatches = {{
    name: (_installed_version(name), expected)
    for name, expected in _EXPECTED_VERSIONS.items()
    if _installed_version(name) != expected
}}

if _mismatches:
    if not _IN_COLAB:
        raise RuntimeError(
            "Pinned Colab packages are not active: "
            + _json.dumps(_mismatches, sort_keys=True)
            + "\\nCreate an isolated environment from configs/colab-runtime.json."
        )
    if _RESTART_MARKER.exists():
        raise RuntimeError(
            "The pinned installation is still inconsistent after the controlled "
            "restart; refusing to restart again. Details: "
            + _json.dumps(_mismatches, sort_keys=True)
        )

    _uv = _shutil.which("uv")
    if _uv is None:
        print(f"Bootstrapping uv=={{_UV_BOOTSTRAP_VERSION}}...")
        _subprocess.run(
            [
                _sys.executable,
                "-m",
                "pip",
                "install",
                "--quiet",
                f"uv=={{_UV_BOOTSTRAP_VERSION}}",
            ],
            check=True,
        )
        _uv = _shutil.which("uv")
    if _uv is None:
        raise RuntimeError("uv was installed but its executable was not found.")

    print("Creating an isolated pinned JAX/Flax environment:", *_REQUIREMENTS)
    _subprocess.run(
        [
            _uv,
            "venv",
            "--clear",
            "--python",
            _sys.executable,
            str(_ENV_ROOT),
        ],
        check=True,
    )
    _subprocess.run(
        [
            _uv,
            "pip",
            "install",
            "--python",
            str(_ENV_PYTHON),
            "--upgrade",
            *_REQUIREMENTS,
        ],
        check=True,
    )
    _subprocess.run(
        [_uv, "pip", "check", "--python", str(_ENV_PYTHON)],
        check=True,
    )

    _metadata_check = (
        "import importlib.metadata as m, json; "
        f"expected={{_EXPECTED_VERSIONS!r}}; "
        "resolved={{name: m.version(name) for name in expected}}; "
        "assert resolved == expected, (resolved, expected); "
        "print(json.dumps(resolved, sort_keys=True))"
    )
    _subprocess.run(
        [_ENV_PYTHON, "-c", _metadata_check],
        check=True,
    )
    _PTH_PATH.write_text(_PTH_CONTENT)

    _RESTART_MARKER.write_text(
        _json.dumps(
            {{"fingerprint": _COLAB_FINGERPRINT, "packages": _EXPECTED_VERSIONS}},
            sort_keys=True,
        )
    )
    print(
        "Pinned packages installed and dependency checks passed. "
        "Colab will now restart once. After reconnecting, run all cells again."
    )
    _os.kill(_os.getpid(), _signal.SIGKILL)

if _IN_COLAB and _ENV_SITE_PACKAGES.is_dir():
    if not _PTH_PATH.is_file() or _PTH_PATH.read_text() != _PTH_CONTENT:
        _PTH_PATH.write_text(_PTH_CONTENT)

print("Pinned Colab environment is already installed; no restart is needed.")
"""


def _json_literal(value: object) -> str:
    return json.dumps(value, indent=4, sort_keys=True)


def validation_block(*, require_parent_gpu: bool) -> str:
    if require_parent_gpu:
        return """# COLAB_RUNTIME_VALIDATE_GPU_V1
_resolved_versions = {
    name: _metadata.version(name)
    for name in _EXPECTED_VERSIONS
}
assert _resolved_versions == _EXPECTED_VERSIONS, _resolved_versions

import jax
import jax.numpy as jnp
import numpy as np
import optax
from flax import nnx
import flax as _flax

assert jax.__version__ == _EXPECTED_VERSIONS["jax"]
assert _flax.__version__ == _EXPECTED_VERSIONS["flax"]
assert optax.__version__ == _EXPECTED_VERSIONS["optax"]
assert np.__version__ == _EXPECTED_VERSIONS["numpy"]

_backend = jax.default_backend()
_devices = jax.devices()
if _backend != "gpu" or not any(device.platform == "gpu" for device in _devices):
    raise RuntimeError(
        f"JAX backend is {_backend!r}, not 'gpu'. "
        "Select Runtime → Change runtime type → T4 GPU and run setup again."
    )
_matrix_product = jnp.ones((128, 128), dtype=jnp.float32) @ jnp.ones(
    (128, 128), dtype=jnp.float32
)
jax.block_until_ready(_matrix_product)
if _matrix_product.device.platform != "gpu":
    raise RuntimeError("The validation matrix multiplication did not execute on the GPU.")

_nnx_probe = nnx.Linear(4, 4, rngs=nnx.Rngs(0))
_nnx_graphdef, _nnx_state = nnx.split(_nnx_probe)
_nnx_restored = nnx.merge(_nnx_graphdef, _nnx_state)
assert _nnx_restored(jnp.ones((1, 4), dtype=jnp.float32)).shape == (1, 4)

print("JAX:", _resolved_versions["jax"])
print("JAXlib:", _resolved_versions["jaxlib"])
print("Flax:", _resolved_versions["flax"])
print("Optax:", _resolved_versions["optax"])
print("NumPy:", _resolved_versions["numpy"])
print("Backend:", _backend)
print("Device:", _devices[0].device_kind)
print("GPU matrix multiplication and Flax NNX split/merge: passed")
"""

    return """# COLAB_RUNTIME_VALIDATE_GPU_WORKER_V1
_GPU_PROBE = r'''
import importlib.metadata as metadata
import flax
import jax
import jax.numpy as jnp
import numpy as np
import optax
from flax import nnx

expected = {
    "jax": "0.8.1",
    "jaxlib": "0.8.1",
    "jax-cuda12-plugin": "0.8.1",
    "jax-cuda12-pjrt": "0.8.1",
    "flax": "0.12.2",
    "optax": "0.2.6",
    "numpy": "2.3.3",
}
resolved = {name: metadata.version(name) for name in expected}
assert resolved == expected, resolved
assert jax.__version__ == expected["jax"]
assert flax.__version__ == expected["flax"]
assert optax.__version__ == expected["optax"]
assert np.__version__ == expected["numpy"]
if jax.default_backend() != "gpu":
    raise RuntimeError(f"Worker JAX backend is {jax.default_backend()!r}, not 'gpu'.")
devices = jax.devices()
product = jnp.ones((128, 128), dtype=jnp.float32) @ jnp.ones(
    (128, 128), dtype=jnp.float32
)
jax.block_until_ready(product)
if product.device.platform != "gpu":
    raise RuntimeError("Worker validation matrix multiplication did not use the GPU.")
layer = nnx.Linear(4, 4, rngs=nnx.Rngs(0))
graphdef, state = nnx.split(layer)
assert nnx.merge(graphdef, state)(jnp.ones((1, 4))).shape == (1, 4)
print("Worker backend:", jax.default_backend())
print("Worker device:", devices[0].device_kind)
print("Worker GPU matrix multiplication and Flax NNX split/merge: passed")
'''
_probe_environment = os.environ.copy()
_probe_environment.pop("JAX_PLATFORMS", None)
subprocess.run(
    [sys.executable, "-c", _GPU_PROBE],
    check=True,
    env=_probe_environment,
)
"""


def replace_version_checks(source: str, *, notebook_name: str) -> str:
    old_checks = {
        "02_dense_scaling_laws.ipynb": """print("JAX:", jax.__version__)
print("Flax:", __import__("flax").__version__)
print("Optax:", optax.__version__)
print("Devices:", jax.devices())

assert jax.__version__ == "0.7.2"
assert __import__("flax").__version__ == "0.12.0"
assert optax.__version__ == "0.2.6"
assert any(device.platform == "gpu" for device in jax.devices()), (
    "Select Runtime → Change runtime type → T4 GPU, restart, and run all cells."
)
""",
        "03_moe_ragged_dot_t4.ipynb": """print("JAX:", jax.__version__)
print("Flax:", __import__("flax").__version__)
print("Optax:", optax.__version__)
print("Devices:", jax.devices())
subprocess.run(["nvidia-smi"], check=True)

assert jax.__version__ == "0.7.2"
assert __import__("flax").__version__ == "0.12.0"
assert optax.__version__ == "0.2.6"
assert hasattr(jax.lax, "ragged_dot")
assert any(device.platform == "gpu" for device in jax.devices()), (
    "Select Runtime → Change runtime type → T4 GPU, restart, and run all cells."
)
""",
        "04_moe_scaling_t4.ipynb": """print("JAX:", jax.__version__)
print("Flax:", __import__("flax").__version__)
print("Optax:", optax.__version__)
print("Notebook devices:", jax.devices(), "(CPU by design; workers use the T4)")

assert jax.__version__ == "0.7.2"
assert __import__("flax").__version__ == "0.12.0"
assert optax.__version__ == "0.2.6"
assert WORKER.is_file()
""",
    }
    old = old_checks[notebook_name]
    if old not in source and old.rstrip() in source:
        old = old.rstrip()
    if old not in source:
        if "COLAB_RUNTIME_VALIDATE_" in source:
            return source
        raise RuntimeError(f"expected version block not found in {notebook_name}")

    if notebook_name == "04_moe_scaling_t4.ipynb":
        new = """_resolved_versions = {
    name: _metadata.version(name)
    for name in _EXPECTED_VERSIONS
}
assert _resolved_versions == _EXPECTED_VERSIONS, _resolved_versions
assert jax.__version__ == _EXPECTED_VERSIONS["jax"]
assert __import__("flax").__version__ == _EXPECTED_VERSIONS["flax"]
assert optax.__version__ == _EXPECTED_VERSIONS["optax"]
assert np.__version__ == _EXPECTED_VERSIONS["numpy"]
print("JAX:", _resolved_versions["jax"])
print("JAXlib:", _resolved_versions["jaxlib"])
print("Flax:", _resolved_versions["flax"])
print("Optax:", _resolved_versions["optax"])
print("NumPy:", _resolved_versions["numpy"])
print("Notebook backend:", jax.default_backend(), "(CPU by design; workers use the T4)")
assert jax.default_backend() == "cpu"
assert WORKER.is_file()
"""
    else:
        new = ""
        if notebook_name == "03_moe_ragged_dot_t4.ipynb":
            new = "assert hasattr(jax.lax, \"ragged_dot\")\n"
    return source.replace(old, new)


def synchronize_notebook(path: Path, config: dict[str, object]) -> None:
    notebook = nbformat.read(path, 4)
    requirements_by_notebook = config["notebooks"]
    assert isinstance(requirements_by_notebook, dict)
    requirements = requirements_by_notebook[path.name]
    assert isinstance(requirements, list)

    notebook.cells[1].source = SETUP_MARKDOWN
    notebook.cells[2].source = install_source(config, requirements)
    notebook.cells[2].metadata["tags"] = [INSTALL_TAG]

    validation = validation_block(
        require_parent_gpu=path.name != "04_moe_scaling_t4.ipynb"
    )
    import_cell = notebook.cells[3]
    if path.name == "01_build_train_exact_10m.ipynb":
        import_cell.source = validation + """

import csv
import json
import math
import pickle
import re
import time
from pathlib import Path

import matplotlib.pyplot as plt
"""
    else:
        import_cell.source = replace_version_checks(
            import_cell.source, notebook_name=path.name
        )
        if (
            path.name == "02_dense_scaling_laws.ipynb"
            and "import subprocess\n" not in import_cell.source
        ):
            import_cell.source = import_cell.source.replace(
                "import pickle\n", "import pickle\nimport subprocess\n"
            )

        if path.name == "04_moe_scaling_t4.ipynb":
            cpu_line = (
                '# Keep this explanatory notebook process off the T4; '
                "workers remove this override.\n"
            )
            if validation not in import_cell.source:
                import_cell.source = import_cell.source.replace(
                    cpu_line, validation + "\n" + cpu_line
                )
        else:
            import_marker = "import jax\n"
            if validation not in import_cell.source:
                import_cell.source = import_cell.source.replace(
                    import_marker, validation + "\n" + import_marker
                )

    import_cell.metadata["tags"] = [VALIDATE_TAG]
    if path.name == "01_build_train_exact_10m.ipynb":
        synchronize_exact_10m_smoke_test(notebook)
    nbformat.write(notebook, path)


def synchronize_exact_10m_smoke_test(notebook: nbformat.NotebookNode) -> None:
    smoke_indexes = [
        index
        for index, cell in enumerate(notebook.cells)
        if SMOKE_TAG in cell.metadata.get("tags", [])
    ]
    if smoke_indexes:
        smoke_index = smoke_indexes[0]
        notebook.cells[smoke_index - 1].source = SMOKE_MARKDOWN
        notebook.cells[smoke_index].source = SMOKE_SOURCE
    else:
        generation_index = next(
            index
            for index, cell in enumerate(notebook.cells)
            if cell.cell_type == "code"
            and "def generate_from_params(params, prompts):" in cell.source
        )
        markdown_cell = nbformat.v4.new_markdown_cell(SMOKE_MARKDOWN)
        code_cell = nbformat.v4.new_code_cell(SMOKE_SOURCE)
        code_cell.metadata["tags"] = [SMOKE_TAG]
        notebook.cells[generation_index + 1 : generation_index + 1] = [
            markdown_cell,
            code_cell,
        ]

    prediction_cell = next(
        cell
        for cell in notebook.cells
        if cell.cell_type == "code" and "def predict_pair(a, b):" in cell.source
    )
    if "(347, 928)," not in prediction_cell.source:
        prediction_cell.source = prediction_cell.source.replace(
            "    (123, 456),\n",
            "    (123, 456),\n    (347, 928),\n",
        )


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text())
    for notebook_name in config["notebooks"]:
        synchronize_notebook(NOTEBOOK_DIR / notebook_name, config)
        print(f"synchronized {notebook_name}")


if __name__ == "__main__":
    main()
