"""Streamlit Community Cloud application for the released JAX model."""

from __future__ import annotations

import html
from pathlib import Path

import streamlit as st

from input_parser import InputError, parse_addition
from model_runtime import MODEL_REPO_ID, get_runtime

MODEL_URL = f"https://huggingface.co/{MODEL_REPO_ID}"
SOURCE_URL = "https://github.com/marcoharuni/jax-addition-transformer"
STYLE_PATH = Path(__file__).with_name("assets") / "style.css"

st.set_page_config(
    page_title="JAX Addition Transformer",
    page_icon="➕",
    layout="centered",
    initial_sidebar_state="collapsed",
)
st.markdown(f"<style>{STYLE_PATH.read_text()}</style>", unsafe_allow_html=True)
st.markdown(
    """
    <header class="editorial-masthead">
      <p class="eyebrow">A complete-domain arithmetic experiment</p>
      <h1>JAX Addition Transformer</h1>
      <p class="deck">
        A 10,000,000-parameter decoder-only transformer trained for fixed
        three-digit addition. Every numerical answer shown here is generated
        autoregressively by the released JAX checkpoint.
      </p>
    </header>
    <div class="domain-notice">
      <strong>Domain:</strong> addition only; each operand must be a whole
      number from 0 through 999.
    </div>
    """,
    unsafe_allow_html=True,
)

with st.status("Loading public model weights and compiling JAX…", expanded=True) as status:
    runtime = get_runtime()
    status.update(
        label=f"Ready · model loaded and compiled in {runtime.startup_seconds:.2f} s",
        state="complete",
        expanded=False,
    )

st.caption("Try an example")
example_columns = st.columns(4)
examples = (
    "347 + 928",
    "What is 499 plus 501?",
    "Please add 91 and 909",
    "Add 999 and 999",
)
selected_prompt = None
for index, (column, example) in enumerate(zip(example_columns, examples, strict=True)):
    if column.button(example, key=f"example-{index}", use_container_width=True):
        selected_prompt = example

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": (
                "Ask me to add two integers. I accept a few clear phrasings and normalize "
                "them into the model’s fixed-width character prompt."
            ),
            "details": None,
            "error": False,
        }
    ]


def render_message(message: dict) -> None:
    avatar = ":material/add:" if message["role"] == "assistant" else ":material/person:"
    with st.chat_message(message["role"], avatar=avatar):
        if message.get("error"):
            st.warning(message["content"])
        elif message["role"] == "assistant" and message.get("details"):
            details = message["details"]
            st.markdown(
                f"<div class='answer-number'>{html.escape(message['content'])}</div>"
                f"<div class='latency'>Generated by the transformer in "
                f"{float(details['latency_seconds']) * 1000:.1f} ms</div>",
                unsafe_allow_html=True,
            )
            with st.expander("Technical details"):
                st.code(str(details["prompt"]), language=None)
                st.write(
                    "Generated internal digits:",
                    f"`{details['internal_digits']}` (units first)",
                )
                st.caption(
                    f"Public artifact: {runtime.weights_source} · "
                    f"startup peak RSS: {runtime.peak_memory_mb:.1f} MB"
                )
        else:
            st.markdown(message["content"])


for prior_message in st.session_state.messages:
    render_message(prior_message)

typed_prompt = st.chat_input("Ask for an addition, for example: 347 + 928")
prompt = typed_prompt or selected_prompt

if prompt:
    user_message = {"role": "user", "content": prompt, "details": None, "error": False}
    st.session_state.messages.append(user_message)
    render_message(user_message)
    try:
        a, b = parse_addition(prompt)
        with st.spinner("Generating four answer digits…"):
            details = runtime.add_with_details(a, b)
        assistant_message = {
            "role": "assistant",
            "content": str(details["answer"]),
            "details": details,
            "error": False,
        }
    except InputError as exc:
        assistant_message = {
            "role": "assistant",
            "content": f"Unsupported request. {exc}",
            "details": None,
            "error": True,
        }
    except Exception:
        assistant_message = {
            "role": "assistant",
            "content": (
                "The model could not complete this request. "
                "Please try again with two integers from 0 to 999."
            ),
            "details": None,
            "error": True,
        }
    st.session_state.messages.append(assistant_message)
    render_message(assistant_message)

st.divider()
with st.expander("About this model"):
    st.markdown(
        f"""
        Five decoder blocks · width 320 · five attention heads · learned
        positions · tied token head · greedy four-token generation.

        The application downloads `model.safetensors` using anonymous public
        read access from [{MODEL_REPO_ID}]({MODEL_URL}). It does not contain the
        original pickle and does not use Python arithmetic to produce answers.

        [Hugging Face model card]({MODEL_URL}) · [GitHub source]({SOURCE_URL})
        """
    )
